/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermercado;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author ernid
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_num2 = new javax.swing.JButton();
        bt_num1 = new javax.swing.JButton();
        bt_num3 = new javax.swing.JButton();
        bt_num4 = new javax.swing.JButton();
        bt_num5 = new javax.swing.JButton();
        bt_num6 = new javax.swing.JButton();
        bt_num7 = new javax.swing.JButton();
        bt_num8 = new javax.swing.JButton();
        bt_num9 = new javax.swing.JButton();
        bt_cambiarSigno = new javax.swing.JButton();
        bt_num0 = new javax.swing.JButton();
        bt_coma = new javax.swing.JButton();
        bt_igual = new javax.swing.JButton();
        bt_suma = new javax.swing.JButton();
        bt_resta = new javax.swing.JButton();
        bt_multiplicacion = new javax.swing.JButton();
        bt_division = new javax.swing.JButton();
        bt_borrarUno = new javax.swing.JButton();
        bt_borrarTodo = new javax.swing.JButton();
        bt_borrarUltimo = new javax.swing.JButton();
        bt_porcentaje = new javax.swing.JButton();
        bt_raizCuadrada = new javax.swing.JButton();
        bt_elevadoCuadrado = new javax.swing.JButton();
        bt_1entreX = new javax.swing.JButton();
        txf_resultado = new javax.swing.JTextField();
        label_operacion = new javax.swing.JLabel();
        label_historial = new javax.swing.JLabel();
        label_primerNumero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_historial = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");
        setMinimumSize(new java.awt.Dimension(246, 541));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        bt_num2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num2.setText("2");
        bt_num2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num2.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num2.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num2.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num2ActionPerformed(evt);
            }
        });

        bt_num1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num1.setText("1");
        bt_num1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num1.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num1.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num1.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num1ActionPerformed(evt);
            }
        });

        bt_num3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num3.setText("3");
        bt_num3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num3.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num3.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num3.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num3ActionPerformed(evt);
            }
        });

        bt_num4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num4.setText("4");
        bt_num4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num4.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num4.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num4.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num4ActionPerformed(evt);
            }
        });

        bt_num5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num5.setText("5");
        bt_num5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num5.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num5.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num5.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num5ActionPerformed(evt);
            }
        });

        bt_num6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num6.setText("6");
        bt_num6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num6.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num6.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num6.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num6ActionPerformed(evt);
            }
        });

        bt_num7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num7.setText("7");
        bt_num7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num7.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num7.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num7.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num7ActionPerformed(evt);
            }
        });

        bt_num8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num8.setText("8");
        bt_num8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num8.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num8.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num8.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num8ActionPerformed(evt);
            }
        });

        bt_num9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num9.setText("9");
        bt_num9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num9.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num9.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num9.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num9ActionPerformed(evt);
            }
        });

        bt_cambiarSigno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_cambiarSigno.setText("±");
        bt_cambiarSigno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cambiarSigno.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_cambiarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cambiarSignoActionPerformed(evt);
            }
        });

        bt_num0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_num0.setText("0");
        bt_num0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_num0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_num0.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_num0.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_num0.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_num0ActionPerformed(evt);
            }
        });

        bt_coma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_coma.setText(",");
        bt_coma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_coma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_coma.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_coma.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_coma.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_coma.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_coma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_comaActionPerformed(evt);
            }
        });

        bt_igual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_igual.setText("=");
        bt_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_igual.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_igualActionPerformed(evt);
            }
        });

        bt_suma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_suma.setText("+");
        bt_suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_suma.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sumaActionPerformed(evt);
            }
        });

        bt_resta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_resta.setText("-");
        bt_resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_resta.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_resta.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_resta.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_resta.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_restaActionPerformed(evt);
            }
        });

        bt_multiplicacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_multiplicacion.setText("X");
        bt_multiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_multiplicacion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_multiplicacion.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_multiplicacion.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_multiplicacion.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_multiplicacionActionPerformed(evt);
            }
        });

        bt_division.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_division.setText("÷");
        bt_division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_division.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_divisionActionPerformed(evt);
            }
        });

        bt_borrarUno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_borrarUno.setText("<-");
        bt_borrarUno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_borrarUno.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_borrarUno.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_borrarUno.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_borrarUno.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_borrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarUnoActionPerformed(evt);
            }
        });

        bt_borrarTodo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_borrarTodo.setText("C");
        bt_borrarTodo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_borrarTodo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_borrarTodo.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_borrarTodo.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_borrarTodo.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarTodoActionPerformed(evt);
            }
        });

        bt_borrarUltimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_borrarUltimo.setText("CE");
        bt_borrarUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_borrarUltimo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_borrarUltimo.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_borrarUltimo.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_borrarUltimo.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_borrarUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarUltimoActionPerformed(evt);
            }
        });

        bt_porcentaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_porcentaje.setText("%");
        bt_porcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_porcentaje.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_porcentaje.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_porcentaje.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_porcentaje.setPreferredSize(new java.awt.Dimension(49, 37));

        bt_raizCuadrada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_raizCuadrada.setText("√");
        bt_raizCuadrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_raizCuadrada.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_raizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_raizCuadradaActionPerformed(evt);
            }
        });

        bt_elevadoCuadrado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bt_elevadoCuadrado.setText("x²");
        bt_elevadoCuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_elevadoCuadrado.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_elevadoCuadrado.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_elevadoCuadrado.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_elevadoCuadrado.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_elevadoCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_elevadoCuadradoActionPerformed(evt);
            }
        });

        bt_1entreX.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_1entreX.setText("1/x");
        bt_1entreX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_1entreX.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bt_1entreX.setMaximumSize(new java.awt.Dimension(49, 37));
        bt_1entreX.setMinimumSize(new java.awt.Dimension(49, 37));
        bt_1entreX.setPreferredSize(new java.awt.Dimension(49, 37));
        bt_1entreX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1entreXActionPerformed(evt);
            }
        });

        txf_resultado.setEditable(false);
        txf_resultado.setBackground(new java.awt.Color(181, 188, 182));
        txf_resultado.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txf_resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        label_operacion.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        label_operacion.setText("OPERACIÓN");

        label_historial.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        label_historial.setText("HISTORIAL");

        label_primerNumero.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        label_primerNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_primerNumero.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txa_historial.setEditable(false);
        txa_historial.setColumns(1);
        txa_historial.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txa_historial.setLineWrap(true);
        txa_historial.setRows(1);
        txa_historial.setAutoscrolls(false);
        jScrollPane1.setViewportView(txa_historial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cambiarSigno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_borrarUltimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_porcentaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_raizCuadrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_borrarTodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_elevadoCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_borrarUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_coma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_1entreX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_division, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_multiplicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_resta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_suma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_igual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(label_historial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txf_resultado)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_operacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_primerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_historial, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_primerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_porcentaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_raizCuadrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_elevadoCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_1entreX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_borrarUltimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_borrarTodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_borrarUno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_division, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_num7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_multiplicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_num4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_resta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_num1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_suma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_igual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_coma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_num0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cambiarSigno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num1ActionPerformed
        if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "1");
        }
        
    }//GEN-LAST:event_bt_num1ActionPerformed

    private void bt_num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num2ActionPerformed
       if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "2");
        }
    }//GEN-LAST:event_bt_num2ActionPerformed

    private void bt_num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num3ActionPerformed
        if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "3");
        }
    }//GEN-LAST:event_bt_num3ActionPerformed

    private void bt_num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num4ActionPerformed
        if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "4");
        }
    }//GEN-LAST:event_bt_num4ActionPerformed

    private void bt_num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num5ActionPerformed
        if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "5");
        }
    }//GEN-LAST:event_bt_num5ActionPerformed

    private void bt_num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num6ActionPerformed
        if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "6");
        }
    }//GEN-LAST:event_bt_num6ActionPerformed

    private void bt_num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num7ActionPerformed
        if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "7");
        }
    }//GEN-LAST:event_bt_num7ActionPerformed

    private void bt_num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num8ActionPerformed
        if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "8");
        }
    }//GEN-LAST:event_bt_num8ActionPerformed

    private void bt_num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num9ActionPerformed
        if (primerDigitoCero == false || comaInsertada){
            txf_resultado.setText(txf_resultado.getText() + "9");
        }
    }//GEN-LAST:event_bt_num9ActionPerformed

    private void bt_num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_num0ActionPerformed
        if (txf_resultado.getText().equals("") && primerDigitoCero == false){
            txf_resultado.setText(txf_resultado.getText() + "0");
            primerDigitoCero = true;
        }
        else if(txf_resultado.getText().equals("0") == false){
            txf_resultado.setText(txf_resultado.getText() + "0");
        }
    }//GEN-LAST:event_bt_num0ActionPerformed

    private void bt_comaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_comaActionPerformed
        if (comaInsertada == false && txf_resultado.getText().equals("") == false){
            txf_resultado.setText(txf_resultado.getText() + ",");
            comaInsertada = true;
        }
    }//GEN-LAST:event_bt_comaActionPerformed

    private void bt_borrarUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarUltimoActionPerformed
        txf_resultado.setText("");
        resetearValores();
    }//GEN-LAST:event_bt_borrarUltimoActionPerformed

    private void bt_borrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarUnoActionPerformed
        if (txf_resultado.getText().length() >= 2){
            char caracterAborrar = txf_resultado.getText().charAt( (txf_resultado.getText().length()-1) );
            if(caracterAborrar == ',' && esNegativo && primerDigitoCero){
                bt_cambiarSignoActionPerformed(evt);
            }
            System.out.println("Valor de primerDigitoCero: " + primerDigitoCero);
            System.out.println("Valor de comaInsertada: " + comaInsertada);
            if(caracterAborrar == ',' && primerDigitoCero){
                txf_resultado.setText("");
                resetearValores();
            }else{
                txf_resultado.setText(txf_resultado.getText().substring(0, txf_resultado.getText().length()-1));
            }
            if(caracterAborrar == ','){
                comaInsertada = false;
            }
        }else{
            txf_resultado.setText("");
            resetearValores();
        }
    }//GEN-LAST:event_bt_borrarUnoActionPerformed

    private void bt_cambiarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cambiarSignoActionPerformed
        if (txf_resultado.getText().length() >=1){
            if (txf_resultado.getText().charAt(0) != '0' || comaInsertada){
                if (esNegativo && txf_resultado.getText().length() >=2){
                    //Si ya es negativo se le quita el signo
                    txf_resultado.setText(txf_resultado.getText().substring(1));
                    esNegativo = false;
                }else{
                    txf_resultado.setText("-" + txf_resultado.getText());
                    esNegativo = true;
                }
            }  
        }
    }//GEN-LAST:event_bt_cambiarSignoActionPerformed

    private void bt_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sumaActionPerformed
        if (numeroAux.equals("")){
            numeroAux = txf_resultado.getText();
            label_primerNumero.setText(numeroAux);
            txf_resultado.setText("");
            tipoOperacion = "suma"; 
        }else{
           bt_igualActionPerformed(evt); 
        }
        resetearValores();
        
    }//GEN-LAST:event_bt_sumaActionPerformed

    private void bt_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_igualActionPerformed
        if (numeroAux.equals("") == false){
            numeroAux = numeroAux.replace(',', '.');
            txf_resultado.setText(txf_resultado.getText().replace(',', '.'));
            Operacion nuevaOperacion = new Operacion(Double.parseDouble(numeroAux), Double.parseDouble(txf_resultado.getText()), tipoOperacion);
            label_primerNumero.setText(nuevaOperacion+ "");
            String resultado = "" + nuevaOperacion.getResultado();
            txf_resultado.setText(resultado.replace('.', ','));
            numeroAux = "";
            anadirHistorial(nuevaOperacion);
        }else{
           txf_resultado.setText(txf_resultado.getText().replace(',', '.'));
           Operacion nuevaOperacion = new Operacion(Double.parseDouble(txf_resultado.getText()), tipoOperacion);
           label_primerNumero.setText(nuevaOperacion+ "");
           String resultado = "" + nuevaOperacion.getResultado();
           txf_resultado.setText(resultado.replace('.', ','));
           anadirHistorial(nuevaOperacion);
        }
    }//GEN-LAST:event_bt_igualActionPerformed

    private void bt_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_restaActionPerformed
       if (numeroAux.equals("")){
            numeroAux = txf_resultado.getText();
            label_primerNumero.setText(numeroAux);
            txf_resultado.setText("");
            tipoOperacion = "resta"; 
        }else{
           bt_igualActionPerformed(evt); 
        }
        resetearValores();
    }//GEN-LAST:event_bt_restaActionPerformed

    private void bt_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_multiplicacionActionPerformed
        if (numeroAux.equals("")){
            numeroAux = txf_resultado.getText();
            label_primerNumero.setText(numeroAux);
            txf_resultado.setText("");
            tipoOperacion = "multiplicacion"; 
        }else{
           bt_igualActionPerformed(evt); 
        }
        resetearValores();
    }//GEN-LAST:event_bt_multiplicacionActionPerformed

    private void bt_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_divisionActionPerformed
        if (numeroAux.equals("")){
            numeroAux = txf_resultado.getText();
            label_primerNumero.setText(numeroAux);
            txf_resultado.setText("");
            tipoOperacion = "division"; 
        }else{
           bt_igualActionPerformed(evt); 
        }
        resetearValores();
    }//GEN-LAST:event_bt_divisionActionPerformed

    private void bt_borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarTodoActionPerformed
        txf_resultado.setText("");
        label_primerNumero.setText("");
        numeroAux = "";
        resetearValores();
    }//GEN-LAST:event_bt_borrarTodoActionPerformed

    private void bt_raizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_raizCuadradaActionPerformed
        tipoOperacion = "raizCuadrada";
        bt_igualActionPerformed(evt); 
        resetearValores();
    }//GEN-LAST:event_bt_raizCuadradaActionPerformed

    private void bt_1entreXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1entreXActionPerformed
        tipoOperacion = "unoEntreX";
        bt_igualActionPerformed(evt); 
        resetearValores();
    }//GEN-LAST:event_bt_1entreXActionPerformed

    private void bt_elevadoCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_elevadoCuadradoActionPerformed
        tipoOperacion = "alCuadrado";
        bt_igualActionPerformed(evt); 
        resetearValores();
    }//GEN-LAST:event_bt_elevadoCuadradoActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        char teclaPulsada = evt.getKeyChar();
        if (teclaPulsada == '1'){
            //bt_num1ActionPerformed(new java.awt.event.ActionEvent);
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_1entreX;
    private javax.swing.JButton bt_borrarTodo;
    private javax.swing.JButton bt_borrarUltimo;
    private javax.swing.JButton bt_borrarUno;
    private javax.swing.JButton bt_cambiarSigno;
    private javax.swing.JButton bt_coma;
    private javax.swing.JButton bt_division;
    private javax.swing.JButton bt_elevadoCuadrado;
    private javax.swing.JButton bt_igual;
    private javax.swing.JButton bt_multiplicacion;
    private javax.swing.JButton bt_num0;
    private javax.swing.JButton bt_num1;
    private javax.swing.JButton bt_num2;
    private javax.swing.JButton bt_num3;
    private javax.swing.JButton bt_num4;
    private javax.swing.JButton bt_num5;
    private javax.swing.JButton bt_num6;
    private javax.swing.JButton bt_num7;
    private javax.swing.JButton bt_num8;
    private javax.swing.JButton bt_num9;
    private javax.swing.JButton bt_porcentaje;
    private javax.swing.JButton bt_raizCuadrada;
    private javax.swing.JButton bt_resta;
    private javax.swing.JButton bt_suma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_historial;
    private javax.swing.JLabel label_operacion;
    private javax.swing.JLabel label_primerNumero;
    private javax.swing.JTextArea txa_historial;
    private javax.swing.JTextField txf_resultado;
    // End of variables declaration//GEN-END:variables
    
    private String numero = "";
    private String numeroAux = "";
    private boolean comaInsertada = false;
    private boolean primerDigitoCero = false;
    private boolean esNegativo = false;
    private String tipoOperacion = "";
    
    int posicionActual_historial = 0;
    Operacion[] operaciones_historial = new Operacion[3];
    private void anadirHistorial(Operacion registrarOperacion){
        txa_historial.setText("");
        operaciones_historial[posicionActual_historial] = registrarOperacion;
        for (int i=0; i<operaciones_historial.length; i++){
            if (operaciones_historial[i] != null){
                if (i == operaciones_historial.length-1){
                    txa_historial.setText(txa_historial.getText() + operaciones_historial[i].toString());
                }else{
                    txa_historial.setText(txa_historial.getText() + operaciones_historial[i].toString()+ "\n");
                }
            }
        }
        if (posicionActual_historial == 2){
            posicionActual_historial = 0;
            for (int i=1; i<operaciones_historial.length; i++){
                operaciones_historial[i] = null;
            }
        }else{
            posicionActual_historial++;
        }
    }
    private void resetearValores(){
        comaInsertada = false;
        primerDigitoCero = false;
        esNegativo = false;
    }
}
