/*
* Inicio del programa, comprueba si existe el archivo de configuración
* En caso de no existir ofrece un asistente de configuración
*/
package supermercado;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class Inicio extends javax.swing.JFrame {

    private Conexion conexion;
    public Inicio() {
        initComponents();
        cargarConfiguracion();
        comprobarConexion();
        
    }
    private void cargarConfiguracion(){
        try {
            ObjectInputStream leerConfiguracion = new ObjectInputStream(new FileInputStream(new File("configuracion.conf")));
            GuardarConexion leerConexionGuardada = (GuardarConexion) leerConfiguracion.readObject();
            conexion = leerConexionGuardada.cargarConexion();
        } catch (IOException| ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se ha podido leer el fichero configuracion.conf","Error", JOptionPane.WARNING_MESSAGE);
        }  

    }
    private void guardarConfiguracion(){
        try {
            GuardarConexion guardarConexion = conexion.guardarDatosConexion();
            ObjectOutputStream guardarFichero = new ObjectOutputStream(new FileOutputStream(new File("configuracion.conf")));
            guardarFichero.writeObject(guardarConexion);
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Guardar Configuracion\n No se ha podido escribir el fichero configuracion.conf \n error: " + ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void comprobarConexion(){
        if (conexion!= null){
            conexion.volverConectar();
        }
        if (conexion!= null && conexion.comprobarConexion()){

            Principal principal = new Principal(conexion);
            principal.setVisible(true);
            
        }else{
            this.setVisible(true);
            this.add(asistente);
            asistente.setBounds(0, 0, 500, 300);
            asistente.setVisible(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asistente = new javax.swing.JPanel();
        bt_nuevaConexion = new javax.swing.JButton();
        lb_nuevaConexion = new javax.swing.JLabel();
        lb_leerConfiguraciondat = new javax.swing.JLabel();
        bt_leerConfiguraciondat = new javax.swing.JButton();
        lb_descripcion_paso1 = new javax.swing.JLabel();
        lb_asistente = new javax.swing.JLabel();
        nuevaConexion_paso1 = new javax.swing.JPanel();
        lb_conexion = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_eslogan = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        txf_eslogan = new javax.swing.JTextField();
        lb_logotipo = new javax.swing.JLabel();
        bt_cargarImagenLogotipo = new javax.swing.JButton();
        scroll_imagenLogotipo = new javax.swing.JScrollPane();
        lb_imagenLogotipo = new javax.swing.JLabel();
        lb_nombreBaseDatos = new javax.swing.JLabel();
        txf_nombreBaseDatos = new javax.swing.JTextField();
        lb_direccion = new javax.swing.JLabel();
        txf_direccion = new javax.swing.JTextField();
        lb_puerto = new javax.swing.JLabel();
        txf_puerto = new javax.swing.JTextField();
        lb_usuario = new javax.swing.JLabel();
        txf_usuario = new javax.swing.JTextField();
        lb_baseDatos = new javax.swing.JLabel();
        lb_contrasena = new javax.swing.JLabel();
        passf_contrasena = new javax.swing.JPasswordField();
        lb_empresa = new javax.swing.JLabel();
        bt_cargarDatosPrueba = new javax.swing.JButton();
        bt_borrar = new javax.swing.JButton();
        bt_continuar = new javax.swing.JButton();

        bt_nuevaConexion.setText("Crear una nueva conexión");
        bt_nuevaConexion.setMaximumSize(new java.awt.Dimension(177, 23));
        bt_nuevaConexion.setMinimumSize(new java.awt.Dimension(177, 23));
        bt_nuevaConexion.setPreferredSize(new java.awt.Dimension(177, 23));
        bt_nuevaConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevaConexionActionPerformed(evt);
            }
        });

        lb_nuevaConexion.setText("Inicia el asistente para configurar una nueva conexión");

        lb_leerConfiguraciondat.setText("Intentar leer de nuevo el fichero configuracion.conf");

        bt_leerConfiguraciondat.setText("Leer fichero configuracion.dat");
        bt_leerConfiguraciondat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_leerConfiguraciondatActionPerformed(evt);
            }
        });

        lb_descripcion_paso1.setForeground(new java.awt.Color(159, 63, 63));
        lb_descripcion_paso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_descripcion_paso1.setText("No se ha detectado ninguna configuración con la base de datos, elija una opción");

        lb_asistente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_asistente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_asistente.setText("ASISTENTE");
        lb_asistente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout asistenteLayout = new javax.swing.GroupLayout(asistente);
        asistente.setLayout(asistenteLayout);
        asistenteLayout.setHorizontalGroup(
            asistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asistenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_asistente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_descripcion_paso1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(asistenteLayout.createSequentialGroup()
                        .addGroup(asistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_nuevaConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_leerConfiguraciondat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(asistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_leerConfiguraciondat, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(lb_nuevaConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        asistenteLayout.setVerticalGroup(
            asistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asistenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_asistente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_descripcion_paso1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_leerConfiguraciondat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(lb_leerConfiguraciondat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_nuevaConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nuevaConexion))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lb_conexion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lb_conexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_conexion.setText("Nueva conexíon");
        lb_conexion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nombre.setText("Nombre");

        lb_eslogan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_eslogan.setText("Eslogan");

        txf_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txf_eslogan.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lb_logotipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_logotipo.setText("Logotipo");

        bt_cargarImagenLogotipo.setText("Cargar imagen ...");
        bt_cargarImagenLogotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cargarImagenLogotipoActionPerformed(evt);
            }
        });

        scroll_imagenLogotipo.setViewportView(lb_imagenLogotipo);

        lb_nombreBaseDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nombreBaseDatos.setText("Nombre de la base de datos");

        txf_nombreBaseDatos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lb_direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_direccion.setText("Dirección");

        txf_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txf_direccion.setText("localhost");

        lb_puerto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_puerto.setText("Puerto");

        txf_puerto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txf_puerto.setText("3306");

        lb_usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_usuario.setText("Usuario");

        txf_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lb_baseDatos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_baseDatos.setText("Base de datos");

        lb_contrasena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_contrasena.setText("Contraseña");

        passf_contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lb_empresa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_empresa.setText("Empresa");

        bt_cargarDatosPrueba.setText("Cargar base de datos con productos de prueba (requiere conexion a internet)");
        bt_cargarDatosPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cargarDatosPruebaActionPerformed(evt);
            }
        });

        bt_borrar.setText("Borrar");
        bt_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_borrarActionPerformed(evt);
            }
        });

        bt_continuar.setText("Continuar");
        bt_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_continuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevaConexion_paso1Layout = new javax.swing.GroupLayout(nuevaConexion_paso1);
        nuevaConexion_paso1.setLayout(nuevaConexion_paso1Layout);
        nuevaConexion_paso1Layout.setHorizontalGroup(
            nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cargarDatosPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_conexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                        .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(lb_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_usuario)
                            .addComponent(passf_contrasena)))
                    .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                        .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_empresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(lb_eslogan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_logotipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_nombre)
                            .addComponent(txf_eslogan)
                            .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                                .addComponent(scroll_imagenLogotipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_cargarImagenLogotipo))))
                    .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                        .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_puerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_baseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_nombreBaseDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(lb_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txf_direccion)
                                    .addComponent(txf_nombreBaseDatos)))
                            .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txf_puerto))))
                    .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(bt_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(bt_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addContainerGap())
        );
        nuevaConexion_paso1Layout.setVerticalGroup(
            nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_empresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_eslogan)
                    .addComponent(txf_eslogan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(bt_cargarImagenLogotipo))
                    .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll_imagenLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_logotipo))))
                .addGap(18, 18, 18)
                .addComponent(lb_baseDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_direccion)
                    .addComponent(txf_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txf_nombreBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevaConexion_paso1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lb_nombreBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_puerto)
                    .addGroup(nuevaConexion_paso1Layout.createSequentialGroup()
                        .addComponent(txf_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_usuario))))
                .addGap(18, 18, 18)
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_contrasena)
                    .addComponent(passf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_cargarDatosPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nuevaConexion_paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asistente de configuración");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_nuevaConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevaConexionActionPerformed
        asistente.setVisible(false);
        this.add(nuevaConexion_paso1);
        nuevaConexion_paso1.setVisible(true);
        nuevaConexion_paso1.setBounds(0, 0, 460, 750);
        this.setBounds(0, 0, 480, 780);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_bt_nuevaConexionActionPerformed

    private void bt_cargarDatosPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cargarDatosPruebaActionPerformed
        txf_direccion.setText("13.81.14.51");
        txf_nombreBaseDatos.setText("proyecto");
        txf_puerto.setText("3306");
        txf_usuario.setText("proyecto");
        passf_contrasena.setText("galileo");
    }//GEN-LAST:event_bt_cargarDatosPruebaActionPerformed

    private void bt_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_borrarActionPerformed
        txf_nombre.setText("");
        txf_eslogan.setText("");
        lb_imagenLogotipo.setIcon(null);
        
        txf_direccion.setText("");
        txf_nombreBaseDatos.setText("");
        txf_puerto.setText("");
        txf_puerto.setText("");
        txf_usuario.setText("");
        passf_contrasena.setText("");
    }//GEN-LAST:event_bt_borrarActionPerformed

    private void bt_cargarImagenLogotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cargarImagenLogotipoActionPerformed
        JFileChooser elegirFichero = new JFileChooser();
        int seleccion = elegirFichero.showOpenDialog(null);
        if (seleccion == JFileChooser.APPROVE_OPTION){
            File ficheroElegido = elegirFichero.getSelectedFile();
            ImageIcon imagenElegida = new ImageIcon(ficheroElegido.getAbsolutePath());
            lb_imagenLogotipo.setIcon(imagenElegida);
            
            if (imagenElegida.getIconHeight()>0){
                JOptionPane.showMessageDialog(this, "Imagen cargada correctamente", "Operación completada", JOptionPane.INFORMATION_MESSAGE);
            }else{
                 JOptionPane.showMessageDialog(this, "No se ha podido cargar la imagen correctamente", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_bt_cargarImagenLogotipoActionPerformed

    private void bt_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_continuarActionPerformed
        conexion = new Conexion(txf_nombre.getText(), txf_eslogan.getText(), (ImageIcon) lb_imagenLogotipo.getIcon(), txf_nombreBaseDatos.getText(), 
                txf_direccion.getText(), Integer.parseInt(txf_puerto.getText()), txf_usuario.getText(), String.valueOf(passf_contrasena.getPassword()));
        
        if (conexion.comprobarConexion()){
            JOptionPane.showMessageDialog(this, "Conexión establecida correctamente", "Operación completada", JOptionPane.INFORMATION_MESSAGE);
            guardarConfiguracion();
            comprobarConexion();
        }else{
            JOptionPane.showMessageDialog(this, "No se ha podido conectar a la base de datos, error:\n " + conexion.getDescripcionErrorConexion(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_continuarActionPerformed

    private void bt_leerConfiguraciondatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_leerConfiguraciondatActionPerformed
        cargarConfiguracion();
        comprobarConexion();
    }//GEN-LAST:event_bt_leerConfiguraciondatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asistente;
    private javax.swing.JButton bt_borrar;
    private javax.swing.JButton bt_cargarDatosPrueba;
    private javax.swing.JButton bt_cargarImagenLogotipo;
    private javax.swing.JButton bt_continuar;
    private javax.swing.JButton bt_leerConfiguraciondat;
    private javax.swing.JButton bt_nuevaConexion;
    private javax.swing.JLabel lb_asistente;
    private javax.swing.JLabel lb_baseDatos;
    private javax.swing.JLabel lb_conexion;
    private javax.swing.JLabel lb_contrasena;
    private javax.swing.JLabel lb_descripcion_paso1;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_empresa;
    private javax.swing.JLabel lb_eslogan;
    private javax.swing.JLabel lb_imagenLogotipo;
    private javax.swing.JLabel lb_leerConfiguraciondat;
    private javax.swing.JLabel lb_logotipo;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_nombreBaseDatos;
    private javax.swing.JLabel lb_nuevaConexion;
    private javax.swing.JLabel lb_puerto;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPanel nuevaConexion_paso1;
    private javax.swing.JPasswordField passf_contrasena;
    private javax.swing.JScrollPane scroll_imagenLogotipo;
    private javax.swing.JTextField txf_direccion;
    private javax.swing.JTextField txf_eslogan;
    private javax.swing.JTextField txf_nombre;
    private javax.swing.JTextField txf_nombreBaseDatos;
    private javax.swing.JTextField txf_puerto;
    private javax.swing.JTextField txf_usuario;
    // End of variables declaration//GEN-END:variables
}
