
package supermercado;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Principal extends javax.swing.JFrame {

    private Connection conexionBaseDatos;
    private Conexion conexion;
    private ResultSet resulset;
    private Statement statement;
    private ArrayList<Empleado> empleados = new ArrayList<>();
    private Empleado empleadoActual;
    public Principal(Conexion conexion) {
        this.conexion = conexion;
        conexionBaseDatos = conexion.getConexion();
        initComponents();
        cargarDatosEmpresa();
        cargarComboUsuarios();
    }


    private void cargarDatosEmpresa(){
        lb_logoEmpresa.setIcon(conexion.getLogoEmpresa());
        this.setTitle(conexion.getNombreEmpresa()+" - Login");
        lb_nombreEmpresa.setText(conexion.getNombreEmpresa()+" - Login");
        lb_eslogan.setText(conexion.getEsloganEmpresa());
       
        try {
            statement = this.conexionBaseDatos.createStatement();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    private void cargarArrayListEmpleados(){
        empleados = new ArrayList<>();
        try {
            empleados = Empleado.cargarEmpleados(conexionBaseDatos);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al leer los datos en la base de datos:\n " + ex.getMessage(), "Error al leer", JOptionPane.WARNING_MESSAGE);
        }  
    }
    private void cargarComboUsuarios(){
        DefaultComboBoxModel<Empleado> modeloCombo = (DefaultComboBoxModel) cmb_usuarios.getModel();
        cargarArrayListEmpleados();
        for (Empleado empleado : empleados) {
            modeloCombo.addElement(empleado);
        }
            
        
    }
    private void iniciarPanelOpciones(){
        panel_elegirPermisos.setVisible(false);
        this.add(panel_opciones);
        panel_opciones.setBounds(10, 202, 780, 387);
        panel_opciones.setVisible(true);
        this.setTitle(conexion.getNombreEmpresa()+" - Opciones");
        lb_nombreEmpresa.setText(conexion.getNombreEmpresa()+" - Opciones");
        if (empleadoActual.getPuesto().equals("empleado")){
            bt_administrarArticulos.setEnabled(false);
            bt_administrarCategorias.setEnabled(false);
            bt_administrarDescuentos.setEnabled(false);
            bt_administrarEmpleados.setEnabled(false);
            bt_registroVentas.setEnabled(false);
            lb_avisoPermisos.setText("Se ha desactivado el acceso a determinadas secciones debido a la limitación de permisos");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_opciones = new javax.swing.JPanel();
        bt_administrarEmpleados = new javax.swing.JButton();
        bt_administrarDescuentos = new javax.swing.JButton();
        bt_administrarCategorias = new javax.swing.JButton();
        bt_administrarArticulos = new javax.swing.JButton();
        bt_registroVentas = new javax.swing.JButton();
        bt_iniciarVentas = new javax.swing.JButton();
        bt_terminar = new javax.swing.JButton();
        lb_avisoPermisos = new javax.swing.JLabel();
        lb_nombreEmpresa = new javax.swing.JLabel();
        scroll_logoEmpresa = new javax.swing.JScrollPane();
        lb_logoEmpresa = new javax.swing.JLabel();
        lb_eslogan = new javax.swing.JLabel();
        panel_elegirPermisos = new javax.swing.JPanel();
        lb_infoAutenticar = new javax.swing.JLabel();
        lb_usuarioCargarPermisos = new javax.swing.JLabel();
        lb_contrasenaCargarPermisos = new javax.swing.JLabel();
        cmb_usuarios = new javax.swing.JComboBox<>();
        lb_infotipoPermiso = new javax.swing.JLabel();
        lb_tipoPermiso = new javax.swing.JLabel();
        passf_contrasena = new javax.swing.JPasswordField();
        bt_entrar = new javax.swing.JButton();

        panel_opciones.setMinimumSize(new java.awt.Dimension(780, 387));
        panel_opciones.setPreferredSize(new java.awt.Dimension(780, 387));
        panel_opciones.setLayout(null);

        bt_administrarEmpleados.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt_administrarEmpleados.setText("Administrar empleados");
        bt_administrarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrarEmpleadosActionPerformed(evt);
            }
        });
        panel_opciones.add(bt_administrarEmpleados);
        bt_administrarEmpleados.setBounds(10, 11, 180, 160);

        bt_administrarDescuentos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt_administrarDescuentos.setText("Administrar descuentos");
        bt_administrarDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrarDescuentosActionPerformed(evt);
            }
        });
        panel_opciones.add(bt_administrarDescuentos);
        bt_administrarDescuentos.setBounds(202, 11, 180, 160);

        bt_administrarCategorias.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt_administrarCategorias.setText("Administrar categorias");
        bt_administrarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrarCategoriasActionPerformed(evt);
            }
        });
        panel_opciones.add(bt_administrarCategorias);
        bt_administrarCategorias.setBounds(394, 11, 180, 160);

        bt_administrarArticulos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt_administrarArticulos.setText("Administrar articulos");
        bt_administrarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_administrarArticulosActionPerformed(evt);
            }
        });
        panel_opciones.add(bt_administrarArticulos);
        bt_administrarArticulos.setBounds(586, 11, 184, 160);

        bt_registroVentas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt_registroVentas.setText("Registro de ventas");
        bt_registroVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registroVentasActionPerformed(evt);
            }
        });
        panel_opciones.add(bt_registroVentas);
        bt_registroVentas.setBounds(10, 216, 180, 160);

        bt_iniciarVentas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt_iniciarVentas.setText("Iniciar terminal de ventas");
        bt_iniciarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_iniciarVentasActionPerformed(evt);
            }
        });
        panel_opciones.add(bt_iniciarVentas);
        bt_iniciarVentas.setBounds(202, 216, 372, 160);

        bt_terminar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt_terminar.setText("TERMINAR");
        bt_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_terminarActionPerformed(evt);
            }
        });
        panel_opciones.add(bt_terminar);
        bt_terminar.setBounds(586, 216, 184, 160);

        lb_avisoPermisos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_avisoPermisos.setText("  ");
        panel_opciones.add(lb_avisoPermisos);
        lb_avisoPermisos.setBounds(10, 190, 760, 14);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setMinimumSize(new java.awt.Dimension(820, 630));
        setPreferredSize(new java.awt.Dimension(820, 630));
        getContentPane().setLayout(null);

        lb_nombreEmpresa.setBackground(new java.awt.Color(162, 198, 162));
        lb_nombreEmpresa.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        lb_nombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nombreEmpresa.setText("- Login");
        lb_nombreEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb_nombreEmpresa.setOpaque(true);
        getContentPane().add(lb_nombreEmpresa);
        lb_nombreEmpresa.setBounds(170, 11, 620, 150);

        scroll_logoEmpresa.setViewportBorder(new javax.swing.border.MatteBorder(null));
        scroll_logoEmpresa.setPreferredSize(new java.awt.Dimension(150, 150));

        lb_logoEmpresa.setPreferredSize(new java.awt.Dimension(120, 120));
        scroll_logoEmpresa.setViewportView(lb_logoEmpresa);

        getContentPane().add(scroll_logoEmpresa);
        scroll_logoEmpresa.setBounds(10, 11, 150, 150);

        lb_eslogan.setBackground(new java.awt.Color(157, 220, 116));
        lb_eslogan.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        lb_eslogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_eslogan.setText("Eslogan");
        lb_eslogan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb_eslogan.setOpaque(true);
        getContentPane().add(lb_eslogan);
        lb_eslogan.setBounds(10, 167, 780, 29);

        panel_elegirPermisos.setLayout(null);

        lb_infoAutenticar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_infoAutenticar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_infoAutenticar.setText("Seleccione el tipo de permiso que desea cargar, a continuación deberá autentificarse.");
        panel_elegirPermisos.add(lb_infoAutenticar);
        lb_infoAutenticar.setBounds(0, 32, 780, 17);

        lb_usuarioCargarPermisos.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lb_usuarioCargarPermisos.setText("Usuario");
        panel_elegirPermisos.add(lb_usuarioCargarPermisos);
        lb_usuarioCargarPermisos.setBounds(10, 94, 79, 30);

        lb_contrasenaCargarPermisos.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lb_contrasenaCargarPermisos.setText("Contraseña");
        panel_elegirPermisos.add(lb_contrasenaCargarPermisos);
        lb_contrasenaCargarPermisos.setBounds(10, 153, 115, 30);

        cmb_usuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmb_usuarios.setModel(new DefaultComboBoxModel());
        cmb_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_usuariosActionPerformed(evt);
            }
        });
        panel_elegirPermisos.add(cmb_usuarios);
        cmb_usuarios.setBounds(215, 88, 400, 41);

        lb_infotipoPermiso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_infotipoPermiso.setText("Tipo de usuario seleccionado: ");
        panel_elegirPermisos.add(lb_infotipoPermiso);
        lb_infotipoPermiso.setBounds(10, 252, 168, 14);

        lb_tipoPermiso.setText("-");
        panel_elegirPermisos.add(lb_tipoPermiso);
        lb_tipoPermiso.setBounds(184, 252, 342, 14);

        passf_contrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passf_contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passf_contrasenaKeyPressed(evt);
            }
        });
        panel_elegirPermisos.add(passf_contrasena);
        passf_contrasena.setBounds(215, 147, 200, 40);

        bt_entrar.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });
        panel_elegirPermisos.add(bt_entrar);
        bt_entrar.setBounds(530, 290, 240, 70);

        getContentPane().add(panel_elegirPermisos);
        panel_elegirPermisos.setBounds(10, 202, 780, 387);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_usuariosActionPerformed
        lb_tipoPermiso.setText(((Empleado) cmb_usuarios.getSelectedItem()).getPuesto());
    }//GEN-LAST:event_cmb_usuariosActionPerformed

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
        Empleado usuario = (Empleado) cmb_usuarios.getSelectedItem();
        empleadoActual = usuario;
        String contrasena = String.valueOf(passf_contrasena.getPassword());
        if ( (usuario.getPuesto().equals("director") && contrasena.equals(Empleado.CONTRASENA_DIRECTOR)) || (usuario.getPuesto().equals("encargado") 
                && contrasena.equals(Empleado.CONTRASENA_ENCARGADO)) || (usuario.getPuesto().equals("empleado") && contrasena.equals(Empleado.CONTRASENA_EMPLEADO))  ){
                iniciarPanelOpciones();
        }else{
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_entrarActionPerformed

    private void passf_contrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passf_contrasenaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            bt_entrarActionPerformed(null);
        }
    }//GEN-LAST:event_passf_contrasenaKeyPressed

    private void bt_administrarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrarEmpleadosActionPerformed
        AdministrarEmpleados administrarEmpleados = new AdministrarEmpleados(conexionBaseDatos);
        administrarEmpleados.setVisible(true);
        
    }//GEN-LAST:event_bt_administrarEmpleadosActionPerformed

    private void bt_administrarDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrarDescuentosActionPerformed
        AdministrarDescuentos administrarDescuentos = new AdministrarDescuentos(conexionBaseDatos);
        administrarDescuentos.setVisible(true);
    }//GEN-LAST:event_bt_administrarDescuentosActionPerformed

    private void bt_administrarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrarCategoriasActionPerformed
        AdministrarCategorias administrarCategorias = new AdministrarCategorias(conexionBaseDatos);
        administrarCategorias.setVisible(true);
    }//GEN-LAST:event_bt_administrarCategoriasActionPerformed

    private void bt_administrarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_administrarArticulosActionPerformed
        AdministrarArticulos administrarArticulos = new AdministrarArticulos(conexionBaseDatos);
        administrarArticulos.setVisible(true);
    }//GEN-LAST:event_bt_administrarArticulosActionPerformed

    private void bt_registroVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registroVentasActionPerformed
        RegistroVentas registroVentas = new RegistroVentas(conexionBaseDatos);
        registroVentas.setVisible(true);
    }//GEN-LAST:event_bt_registroVentasActionPerformed

    private void bt_iniciarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_iniciarVentasActionPerformed
        TerminalVentas terminalVentas = new TerminalVentas(conexionBaseDatos, empleadoActual);
        terminalVentas.setVisible(true);
    }//GEN-LAST:event_bt_iniciarVentasActionPerformed

    private void bt_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_terminarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_terminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_administrarArticulos;
    private javax.swing.JButton bt_administrarCategorias;
    private javax.swing.JButton bt_administrarDescuentos;
    private javax.swing.JButton bt_administrarEmpleados;
    private javax.swing.JButton bt_entrar;
    private javax.swing.JButton bt_iniciarVentas;
    private javax.swing.JButton bt_registroVentas;
    private javax.swing.JButton bt_terminar;
    private javax.swing.JComboBox<String> cmb_usuarios;
    private javax.swing.JLabel lb_avisoPermisos;
    private javax.swing.JLabel lb_contrasenaCargarPermisos;
    private javax.swing.JLabel lb_eslogan;
    private javax.swing.JLabel lb_infoAutenticar;
    private javax.swing.JLabel lb_infotipoPermiso;
    private javax.swing.JLabel lb_logoEmpresa;
    private javax.swing.JLabel lb_nombreEmpresa;
    private javax.swing.JLabel lb_tipoPermiso;
    private javax.swing.JLabel lb_usuarioCargarPermisos;
    private javax.swing.JPanel panel_elegirPermisos;
    private javax.swing.JPanel panel_opciones;
    private javax.swing.JPasswordField passf_contrasena;
    private javax.swing.JScrollPane scroll_logoEmpresa;
    // End of variables declaration//GEN-END:variables
}
